///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();
  static const String imagesBitcoin = 'assets/images/bitcoin.svg';
  static const String imagesCoins = 'assets/images/coins.svg';
  static const String imagesEthereum = 'assets/images/ethereum.svg';
  static const String imagesLineChange = 'assets/images/line_change.svg';
  static const String imagesNFTs1 = 'assets/images/NFTs1.png';
  static const String imagesNFTs2 = 'assets/images/NFTs2.png';
  static const String imagesNFTs3 = 'assets/images/NFTs3.png';
  static const String imagesNFTs4 = 'assets/images/NFTs4.png';
  static const String imagesNFTs5 = 'assets/images/NFTs5.png';
  static const String imagesNFTs6 = 'assets/images/NFTs6.png';
  static const String imagesNotification = 'assets/images/notification.svg';
  static const String imagesPersonProfile = 'assets/images/person_profile.png';
  static const String imagesReceiveMoney = 'assets/images/receive_money.svg';
  static const String imagesRedlineChange = 'assets/images/redline_change.svg';
  static const String imagesSendMoney = 'assets/images/send_money.svg';
  static const String imagesSolona = 'assets/images/solona.svg';

}
